### ISSUE TITLE
Is the map still planned to be available?

### ISSUE THREAD

**Issue by natrius** [Qwant/erdapfel#1474]
Asking because of the german thread in the osm-forum https://community.openstreetmap.org/t/qwant-maps/85450/27

On https://www.qwant.com/ there is no trace to be found. Also, it moved from the known https://qwant.com/maps to https://map.qwant.com/ - so its still there but it seems there is no way to get to the map through the mainpage. 

Btw. thanks for the work you done, i recommended Qwant to plenty of people!

**Comment by QwantAdmin** [comment]
Hi @natrius,
Thank you for your encouragement and your questions.
In the short term, the dedicated Qwant Maps application will no longer be maintained, in favour of developing the mapping experience within the search engine, in particular through searches for places or addresses.
We are gradually updating our service presentation pages to reflect this change in priorities.

**Comment by natrius** [comment]
Thats unfortunate, i'm active on OSM and when i was at an event or presentation people usally asked for an alternative to google maps specifically and i recommended qwant-maps and mapy.cz often and quite some people liked the qwant maps a lot as far as i'm aware. I like that there are at least two to choose from. 

Thanks for the quick answer - i will leave closing this issue up to you :)

**Comment by sfkeller** [comment]
@QwantAdmin : 
I understand that maps should be included in the search engine result page (SERP). 
But that doesn't mean you don't need Qwant Maps anymore, does it? 
What kind of result should “Restaurants in Paris” return if not https://map.qwant.com/ - even if it's perhaps embedded in the SERP?
So please: Keep maintaining https://map.qwant.com/ so that permalinks to it continue to function!
